---
title: "Multivariate covariance generalized linear models for the analysis of experimental data"
author: |
  | Wagner H. Bonat   | Walmes M. Zeviani |
  |:-----------------:|:-----------------:|
  | `wbonat@ufpr.br`  | `walmes@ufpr.br`  |
#author: "Wagner H. Bonat & Walmes M. Zeviani "
date: |
  63^a^ RBras & 17^o^ SEAGRO\
  July 24--28, 2017\
  UFLA, Lavras/MG
lang: pt-BR
# graphics: yes
# classoption:
#   - serif
#   - mathserif
#   - professionalfont
#   - aspectratio=169
# header-includes:
#   - \usepackage{palatino}
#   - \usepackage{inconsolata}
#   - \let\oldframe\frame
#   - \renewcommand\frame[1][allowframebreaks]{\oldframe[#1]}
#   - \setbeamertemplate{frametitle continuation}{}
# output:
#   beamer_presentation:
#     fig_caption: yes
#     fig_crop: no
#     highlight: haddock
#     #includes:
#     #  in_header: preamble-2.tex
#     #incremental: yes
#     #keep_tex: yes
output:
  slidy_presentation:
    css: config/style.css
    footer: McGLMs for experimental data, Bonat & Zeviani (2017)
    highlight: haddock
    includes:
      in_header: config/MathJax.html
---

# Introduction and Outline

## What is this course about

  * Often in experimental studies many outcomes are collected
    simultaneously.
  * Sometimes the outcomes or response variables are of mixed types.
  * Methods for the separate analysis of such outcomes are well
    established in the literature.
    - Continuous and symmetric data: linear regression models.
    - Continuous and assymetric data: gamma and inverse Gaussian
      regression models.
    - Semi-continuous data: Tweedie and zero-inflated regression models.
    - Counting data: Poisson, negative binomial, Poisson-Tweedie
      and $\ldots$ regression models.
    - Bounded data: logistic, probit, beta, simplex
      and $\ldots$  regression models.

## Main goal

  * Purpose of this course is to present the state of art in
    **Multivariate analysis of experimental data based on the
      multivariate covariance generalized linear models class.**

## Learnings objectives

  * After this course participants will be able to
    - identify settings in which a multivariate analysis is required,
    - construct and fit an appropriate multivariate model, and
    - correctly interpret the obtained results.

  * The course will be explanatory rather than mathematically rigorous
    - emphasis is given on sufficient detail in order for participants
      to obtain a clear view on the multivariate models and how they
      should be used in practice.

## Outline

### Part I: Multivariate analysis of Gaussian data (MANOVA)

  * Motivational datasets and research questions.
  * The General Multivariate (Gaussian) Linear Model.
    - Estimation and inference (least squares and MLE).
    - General linear hypotheses.
    - Multivariate hypotheses tests.
    - Computational implementation in $\textsf{R}$.
    - Usage of the $\texttt{lm()}$ and $\texttt{manova()}$ functions.
    - MANOVA in the McGLM framework.
    - The $\texttt{mcglm()}$ function.
    - Worked examples.
    - Assumptions and limitations.
    - Concluding remarks.

### Part II: Multivariate analysis of non-Gaussian data (McGLM)

  * Dealing with non-independent data: Linear covariance models (LCMs).
  * Specifying the matrix linear predictor:
    - Repeated measures.
    - Longitudinal studies.
    - Mixed models.
  * Dealing with non-Gaussian data: Multivariate generalized linear
    models (MGLMs).
  * Estimation and Inference.
  * General linear hypotheses tests.
  * MANOVA-like test for non-Gaussian data.
  * Worked examples.
  * Discussions and extensions.
