---
title: "Simulation study"
author: |
  | Wagner H. Bonat   | Walmes M. Zeviani |
  |:-----------------:|:-----------------:|
  | `wbonat@ufpr.br`  | `walmes@ufpr.br`  |
date: >
  63^a^ RBras & 17^o^ SEAGRO</br>
  July 24--28, 2017</br>
  UFLA, Lavras/MG
---

# The $\chi^2$ asymptotics

## Function prototyping

```{r, include = FALSE}
source("../slides/config/_setup.R")
```
```{r}
#-----------------------------------------------------------------------
# Packages.

rm(list = ls())

library(mvtnorm)
library(latticeExtra)

#-----------------------------------------------------------------------
# The Chi-square asymptotic of the multivariate tests.

#-----------------------------------------------------------------------
# Prototyping: creating a function to run the simulation study.

# Simulation settings.
m <- 3    # Number of responses.
k <- 4    # Number of groups.
rept <- 4 # Repetition of each group.

# Returns the chi-square statistic of each test.
simul_chi <- function(m, k, rept, N = 1000) {
    trt <- gl(k, rept)
    n <- length(trt)
    # Means and covariances.
    mu <- rep(0, m)
    Sigma <- 0.5 * (diag(m) + matrix(1, m, m))
    # Paired samples of the statistics.
    smp <- replicate(N, {
        Y <- rmvnorm(n = length(trt),
                     mean = mu,
                     sigma = Sigma)
        # Sigma of the null model.
        m0 <- lm(Y ~ 1)
        S0 <- var(residuals(m0)) * (n - 1)/n
        # Sigma of the full model.
        m1 <- lm(Y ~ trt)
        S1 <- var(residuals(m1)) * (n - 1)/n
        #------------------------------------
        # Wilks' statistic.
        wil <- -n * log(det(S1)/det(S0))
        #------------------------------------
        # Hotelling-Lawley's statistic.
        hol <- n * sum(diag(solve(S1, S0 - S1)))
        #------------------------------------
        # Pillai's statistic.
        pil <- n * sum(diag(solve(S0, S0 - S1)))
        return(c(wil = wil, hol = hol, pil = pil))
    })
    return(smp)
}

# A sample of the Wilks' lambda statistic.
smp <- simul_chi(m = m, rept = rept, k = k)

# The function to display the legend.
leg <- function(...) {
    legend(...,
           legend = c("Wilks", "Hotelling-Lawley", "Pillai"),
           col = c(2, 4, 3),
           lty = 1,
           bty = "n")
}

# Empirical chi-square distribution vs theoretical.
plot(ecdf(smp[1, ]), col = 2,
     xlab = expression(X^{2} ~ "statistic"),
     ylab = "Empirical CDF",
     main = NULL)
lines(ecdf(smp[2, ]), col = 4)
lines(ecdf(smp[3, ]), col = 3)
curve(pchisq(x, df = m * (k - 1)), add = TRUE, col = 1)
leg("right")

# Get the p-values.
pval <- apply(smp,
              MARGIN = 1,
              FUN = pchisq,
              df = m * (k - 1))
str(pval)

plot(ecdf(pval[, 1]),
     xlab = expression("p-values for the" ~ X^{2} ~ "statistic"),
     ylab = "Empirical CDF",
     col = 2,
     pch = NA,
     main = NULL)
lines(ecdf(pval[, 2]), col = 4, cex = NA)
lines(ecdf(pval[, 3]), col = 3, cex = NA)
segments(0, 0, 1, 1, col = 1)
leg("left")
```

## Running the simulation study

```{r}
#-----------------------------------------------------------------------
# Design settings for a small simulation study.

# k:    number of treatment levels (fixed);
# N:    number of simulations (fixed);
# m:    number of responses (varying);
# rept: repetition per treatment level (varying).
k <- 4
N <- 1000
ds <- expand.grid(m = c(2, 5, 8),
                  rept = c(5, 10, 20))

# Simulation for each design setting case.
res <- by(data = ds,
          INDICES = seq_len(nrow(ds)),
          FUN = function(case) {
              smp <- with(case,
                          simul_chi(m = m,
                                    rept = rept,
                                    k = k,
                                    N = N))
              test <- rownames(smp)
              smp <- c(t(smp))
              data.frame(m = case$m,
                         rept = case$rept,
                         test = rep(test, each = N),
                         smp = smp,
                         pval = pchisq(smp, case$m * (k - 1)))
          })

# Stack to one data frame.
res <- do.call(rbind, res)
res$n <- res$rept * k
res$test <- factor(res$test,
                   levels = c("wil", "hol", "pil"),
                   labels = c("Wilks", "Hotelling-Lawley", "Pillai"))
res_chi <- res
rm(res)

useOuterStrips(
    ecdfplot(~pval | factor(m) + factor(n),
             as.table = TRUE,
             groups = test,
             auto.key = list(columns = 2,
                             title = "Test",
                             cex.title = 1.1),
             xlab = expression("p-values for the" ~
                                   X^{2} ~ "statistic"),
             ylab = "Empirical CDF",
             data = res_chi),
    strip = strip.custom(
        var.name = "Responses",
        strip.names = TRUE,
        sep = " = "),
    strip.left = strip.custom(
        var.name = "Subjects",
        strip.names = TRUE,
        sep = " = ")) +
    layer({
        panel.segments(0, 0, 1, 1, lty = 2, col = 1)
    })
```

# The F approximation

## Running the simulation study

```{r}
#-----------------------------------------------------------------------
# The F approximantion of each multivariate test.

# Each test.
tt <- c("Wilks", "Hotelling-Lawley", "Pillai", "Roy")
# tt <- tt[-4]

# Simulation of data under H_0 and computation of F statistics.
simul_F <- function(m, k, rept, N = 1000) {
    trt <- gl(k, rept)
    mu <- rep(0, m)
    n <- length(trt)
    Sigma <- 0.5 * (diag(m) + matrix(1, m, m))
    # Sample of the statistic.
    smp <- replicate(N, {
        Y <- rmvnorm(n = length(trt),
                     mean = mu,
                     sigma = Sigma)
        m0 <- lm(Y ~ trt)
        pvals <- sapply(tt,
                        FUN = function(test) {
                            # Extract the p-value.
                            anova(m0, test = test)[2, 6]
                        })
        return(pvals)
    })
    return(smp)
}

simul_F(m = 3, k = 4, rept = 10, N = 20)

# Simulation for each design setting case.
res <- by(data = ds,
          INDICES = seq_len(nrow(ds)),
          FUN = function(case) {
              smp <- with(case,
                          simul_F(m = m,
                                  rept = rept,
                                  k = k,
                                  N = N))
              smp <- stack(as.data.frame(t(smp)))
              cbind(data.frame(m = case$m,
                               rept = case$rept),
                    smp)
          })

# Stack to one data frame.
res <- do.call(rbind, res)
res$n <- res$rept * k
names(res)[3:4] <- c("pval", "test")
res$test <- factor(res$test, levels = tt)
res_F <- res
rm(res)

useOuterStrips(
    ecdfplot(~pval | factor(m) + factor(n),
             groups = test,
             auto.key = list(columns = 2,
                             title = "Test",
                             cex.title = 1.1),
             as.table = TRUE,
             xlab = expression("p-values for the" ~
                                   italic(F) ~ "statistic"),
             ylab = "Empirical CDF",
             subset = !is.na(pval),
             data = res_F),
    strip = strip.custom(
        var.name = "Responses",
        strip.names = TRUE,
        sep = " = "),
    strip.left = strip.custom(
        var.name = "Subjects",
        strip.names = TRUE,
        sep = " = ")) +
    layer({
        panel.segments(0, 0, 1, 1, lty = 2, col = 1)
    })

#-----------------------------------------------------------------------
```

# Session information

```{r}
# devtools::session_info()
Sys.time()
cbind(Sys.info())
sessionInfo()
```
