---
title: "Multivariate analysis with canonical scores"
author: |
  ```{r, echo = FALSE, results = "asis"}
  source("../slides/config/yaml-authors.R", print.eval = TRUE)
  ```
date: >
  62^a^ RBras & 17^o^ SEAGRO</br>
  July 24--28, 2017</br>
  UFLA, Lavras/MG
bibliography: ../slides/config/ref.bib
csl: ../slides/config/elsevier-harvard.csl
---

```{r, include = FALSE}
source("../slides/config/_setup.R")
```

# Data description and objectives

  * TODO
  * TODO

```{r, message = FALSE}
#-----------------------------------------------------------------------
# Packages.

rm(list = ls())
library(lattice)
library(latticeExtra)
library(car)
library(candisc)
library(corrplot)
```

# Petal measures

```{r}
#-----------------------------------------------------------------------

scatterplotMatrix(~Sepal.Length + Sepal.Width +
                      Petal.Length + Petal.Width | Species,
                  data = iris,
                  smooth = FALSE,
                  reg.line = FALSE,
                  ellipse = TRUE,
                  by.groups = TRUE,
                  gap = 0,
                  diagonal = "density")

#-----------------------------------------------------------------------
# Petal.Length & Petal.Width.

scatterplotMatrix(~Petal.Length + Petal.Width | Species,
                  data = iris,
                  smooth = FALSE,
                  reg.line = FALSE,
                  ellipse = TRUE,
                  by.groups = TRUE,
                  gap = 0,
                  diagonal = "density")

#-----------------------------------------------------------------------
# MLM fitting.

# Iris full model.
m1 <- lm(cbind(Petal.Length,
               Petal.Width) ~ Species,
         data = iris)

# Iris null model.
m0 <- update(m1, . ~ 1)

# MANOVA with Pillai test.
anova(m1)

# Extract the raw residuals.
r <- residuals(m1)

# Checking the models assumptions on the residuals.
scatterplotMatrix(r,
                  gap = 0,
                  smooth = FALSE,
                  reg.line = FALSE,
                  ellipse = TRUE,
                  diagonal = "qqplot")


#-----------------------------------------------------------------------
# Doing the canonical analysis using eigen decomposition.

# Error SSP of the full and null models.
S_full <- crossprod(residuals(m1))
S_null <- crossprod(residuals(m0))

# Extra SSP due the hypothesis.
S_extr <- S_null - S_full

# Eigen decomposition -> canonical analysis.
ei <- eigen(solve(S_full, S_extr))
ei

# Cumulated proportion.
cumsum(ei$values)/sum(ei$values)

# Scores (canonical variables).
scores <- as.matrix(m1$model[1]) %*% ei$vectors[, 1:2]

# Plot of the scores.
xyplot(scores[, 2] ~ scores[, 1],
       groups = iris$Species,
       grid = TRUE,
       auto.key = list(columns = 3,
                       title = "Species",
                       cex.title = 1),
       xlab = "First canonical dimension",
       ylab = "Second canonical dimension",
       aspect = "iso") +
    layer(panel.ellipse(...))

#-----------------------------------------------------------------------
# Using the `candisc` package.

c1 <- candisc(m1, term = "Species")
str(c1)

summary(c1)

# The canonical scores.
c("my eigen" = xyplot(scores[, 2] ~ scores[, 1],
                      groups = iris$Species,
                      grid = TRUE,
                      auto.key = list(columns = 3,
                                      title = "Species",
                                      cex.title = 1),
                      xlab = "First canonical dimension",
                      ylab = "Second canonical dimension"),
  "candisc" = xyplot(Can2 ~ Can1,
                     groups = Species,
                     data = c1$scores,
                     grid = TRUE,
                     auto.key = list(columns = 3,
                                     title = "Species",
                                     cex.title = 1),
                     xlab = "First canonical dimension",
                     ylab = "Second canonical dimension"),
  layout = c(1, NA))

ei$vectors[, 1:2]
c1$coeffs.raw
c1$coeffs.raw/ei$vectors[, 1:2]

# The plot() method for `candisc` objects.
plot(c1, asp = 1)
grid()

# ATTENTION: upened issue! Study the plot.candisc() function to see
# wheather they scale the vectors.
# getS3method(f = "plot", class = "candisc")

# Scores: canonical variates.
xy_can <-
    xyplot(Can2 ~ Can1,
           groups = Species,
           data = c1$scores,
           xlab = NULL,
           ylab = NULL,
           aspect = "iso",
           auto.key = list(columns = 3),
           grid = TRUE) +
    layer(panel.ellipse(...)) +
    layer(panel.arrows(0, 0,
                       c1$coeffs.raw[, 1],
                       c1$coeffs.raw[, 2],
                       length = 0.1))

xy_ori <-
    xyplot(Petal.Length ~ Petal.Width,
           groups = Species,
           aspect = "iso",
           data = iris,
           grid = TRUE) +
    layer(panel.ellipse(...))

c("Canonical" = xy_can,
  "Original" = xy_ori,
  layout = c(1, 2))

#--------------------------------------------
# Univariate analysis of each canical variate.

an0 <- lm(scores ~ Species, data = iris)
summary(an0)
```

# Sepal measures

```{r}
#-----------------------------------------------------------------------
# Sepal.Length & Sepal.Width.

scatterplotMatrix(~Sepal.Length + Sepal.Width | Species,
                  data = iris,
                  smooth = FALSE,
                  reg.line = FALSE,
                  ellipse = TRUE,
                  by.groups = TRUE,
                  gap = 0,
                  diagonal = "density")

# Iris full model.
m1 <- lm(cbind(Sepal.Length,
               Sepal.Width) ~ Species,
         data = iris)

# Iris null model.
m0 <- update(m1, . ~ 1)

# MANOVA with Pillai test.
anova(m1)

# Extract the raw residuals.
r <- residuals(m1)

# Checking the models assumptions on the residuals.
scatterplotMatrix(r,
                  gap = 0,
                  smooth = FALSE,
                  reg.line = FALSE,
                  ellipse = TRUE,
                  diagonal = "qqplot")

#-----------------------------------------------------------------------
# Doing the canonical analysis using eigen decomposition.

# Error SSP of the full and null models.
S_full <- crossprod(residuals(m1))
S_null <- crossprod(residuals(m0))

# Extra SSP due the hypothesis.
S_extr <- S_null - S_full

# Eigen decomposition -> canonical analysis.
ei <- eigen(solve(S_full, S_extr))
ei

# Cumulated proportion.
cumsum(ei$values)/sum(ei$values)

# Scores (canonical variables).
scores <- as.matrix(m1$model[1]) %*% ei$vectors[, 1:2]

# Plot of the scores.
xyplot(scores[, 2] ~ scores[, 1],
       groups = iris$Species,
       grid = TRUE,
       auto.key = list(columns = 3,
                       title = "Species",
                       cex.title = 1),
       xlab = "First canonical dimension",
       ylab = "Second canonical dimension",
       aspect = "iso") +
    layer(panel.ellipse(...))

#-----------------------------------------------------------------------
# Using the `candisc` package.

c1 <- candisc(m1, term = "Species")
str(c1)

summary(c1)

# The canonical scores.
c("my eigen" = xyplot(scores[, 2] ~ scores[, 1],
                      groups = iris$Species,
                      grid = TRUE,
                      auto.key = list(columns = 3,
                                      title = "Species",
                                      cex.title = 1),
                      xlab = "First canonical dimension",
                      ylab = "Second canonical dimension"),
  "candisc" = xyplot(Can2 ~ Can1,
                     groups = Species,
                     data = c1$scores,
                     grid = TRUE,
                     auto.key = list(columns = 3,
                                     title = "Species",
                                     cex.title = 1),
                     xlab = "First canonical dimension",
                     ylab = "Second canonical dimension"),
  layout = c(1, NA))

ei$vectors[, 1:2]
c1$coeffs.raw
c1$coeffs.raw/ei$vectors[, 1:2]

# The plot() method for `candisc` objects.
plot(c1, asp = 1)
grid()

# ATTENTION: upened issue! Study the plot.candisc() function to see
# wheather they scale the vectors.
# getS3method(f = "plot", class = "candisc")

# Scores: canonical variates.
xy_can <-
    xyplot(Can2 ~ Can1,
           groups = Species,
           data = c1$scores,
           xlab = NULL,
           ylab = NULL,
           aspect = "iso",
           auto.key = list(columns = 3),
           grid = TRUE) +
    layer(panel.ellipse(...)) +
    layer(panel.arrows(0, 0,
                       c1$coeffs.raw[, 1],
                       c1$coeffs.raw[, 2],
                       length = 0.1))

xy_ori <-
    xyplot(Petal.Length ~ Petal.Width,
           groups = Species,
           aspect = "iso",
           data = iris,
           grid = TRUE) +
    layer(panel.ellipse(...))

c("Canonical" = xy_can,
  "Original" = xy_ori,
  layout = c(1, 2))

#--------------------------------------------
# Univariate analysis of each canical variate.

an0 <- lm(scores ~ Species, data = iris)
summary(an0)
```

# References

```{r, echo = FALSE, results = "asis", message = FALSE, warning = FALSE, error = FALSE}
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "html") {
    cat('<!-- Insert the refereces right here! -->',
        '<div id="refs">',
        '</div>\n',
        sep = "\n")
}
```

# Session information

```{r}
# devtools::session_info()
Sys.time()
cbind(Sys.info())
sessionInfo()
```
